package main

import (
	"flag"
	"fmt"
	"os"
)

const initTemplate = `# Virgil local gateway configuration
# Generated by virgil init — edit to fit your setup.

[server]
listen    = "127.0.0.1:8787"
log_level = "info"

[storage]
path           = "./data/virgil.db"
retention_days = 30

[guardrails]
# Limits per agent run — remove or set to 0 for unlimited.
max_requests_per_run   = 100
max_total_tokens_per_run = 200000
max_cost_per_run_usd    = "1.00"

# Installation-wide daily limits (independent of run_id).
max_calls_per_day    = 500
max_cost_per_day_usd = "10.00"

# Uncomment to enable price-based guardrails:
# estimated_cost_per_call_usd      = "0.01"
# estimated_input_tokens_per_call  = 1000
# estimated_output_tokens_per_call = 500

# Allowlists — empty means all are allowed.
# allowed_providers = ["openai"]
# allowed_models    = ["gpt-4o-mini"]

# Example provider: OpenAI
[providers.openai]
type         = "openai"
base_url     = "https://api.openai.com/v1"
model        = "gpt-4o-mini"
capabilities = ["stream", "tools"]
# api_key = "${OPENAI_API_KEY}"   # uncomment and set the env var

# Example provider: Anthropic
# [providers.anthropic]
# type         = "anthropic"
# model        = "claude-3-5-haiku-20241022"
# capabilities = ["stream", "tools"]
# api_key      = "${ANTHROPIC_API_KEY}"
`

func runInit(args []string) error {
	flags := flag.NewFlagSet("init", flag.ContinueOnError)
	output := flags.String("output", "virgil.toml", "output config file path")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if _, err := os.Stat(*output); err == nil {
		return fmt.Errorf("%s already exists; delete it or use --output to choose a different path", *output)
	}
	if err := os.WriteFile(*output, []byte(initTemplate), 0600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	fmt.Printf("Created %s\n", *output)
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit virgil.toml — set your provider api_key (as an env var reference)")
	fmt.Println("  2. export OPENAI_API_KEY=sk-...")
	fmt.Println("  3. virgil serve --config virgil.toml")
	return nil
}
